

export default {
    MONGODB_CONNECTION: process.env.MONGODB_CONNECTION,
    KAFKA_CONNECTION: process.env.KAFKA_CONNECTION,
    KAFKA_TOPIC_LISTEN: process.env.KAFKA_TOPIC_LISTEN,
    KAFKA_TOPIC_SEND: process.env.KAFKA_TOPIC_SEND,
    ETHEREUM_NODE_BASE_URL: process.env.ETHEREUM_NODE_BASE_URL,
    ETHEREUM_SYNC_START_BLOCK: process.env.ETHEREUM_SYNC_START_BLOCK,
}