/**
 * Different constList that used across the project
 */

export const METHOD_GET_ADDRESS = "METHOD_GET_ADDRESS"
export const METHOD_SEND_TRANSACTION = "METHOD_SEND_TRANSACTION"
export const METHOD_GET_ADDRESS_INFO = "METHOD_GET_ADDRESS_INFO"
export const METHOD_GET_TRANSACTION_INFO = "METHOD_GET_TRANSACTION_INFO"
export const METHOD_NEW_BALANCE = "METHOD_NEW_BALANCE"
export const METHOD_NEW_TRANSACTION = "METHOD_NEW_TRANSACTION"
export const METHOD_NEW_MEMPOOL_TX = "METHOD_NEW_MEMPOOL_TX"
export const METHOD_NEW_TX_CONFIRMATION = "METHOD_NEW_TX_CONFIRMATION"
export const METHOD_TX_WENT_INTO_BLOCK = "METHOD_TX_WENT_INTO_BLOCK"